/**********************************************************************
 *  Copyright (c) 2008-2014, Alliance for Sustainable Energy.
 *  All rights reserved.
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 **********************************************************************/

#ifndef MODEL_CONTROLLERMECHANICALVENTILATION_IMPL_HPP
#define MODEL_CONTROLLERMECHANICALVENTILATION_IMPL_HPP

#include "ModelAPI.hpp"
#include "ModelObject_Impl.hpp"

namespace openstudio {
namespace model {

// TODO: Check the following class names against object getters and setters.
class Schedule;
class ControllerOutdoorAir;

namespace detail {

  /** ControllerMechanicalVentilation_Impl is a ModelObject_Impl that is the implementation class for ControllerMechanicalVentilation.*/
  class MODEL_API ControllerMechanicalVentilation_Impl : public ModelObject_Impl {
    Q_OBJECT;

    Q_PROPERTY(bool demandControlledVentilation READ demandControlledVentilation WRITE setDemandControlledVentilation RESET resetDemandControlledVentilation);
    Q_PROPERTY(bool isDemandControlledVentilationDefaulted READ isDemandControlledVentilationDefaulted);

    Q_PROPERTY(std::string systemOutdoorAirMethod READ systemOutdoorAirMethod WRITE setSystemOutdoorAirMethod RESET resetSystemOutdoorAirMethod);
    Q_PROPERTY(bool isSystemOutdoorAirMethodDefaulted READ isSystemOutdoorAirMethodDefaulted);
    Q_PROPERTY(std::vector<std::string> systemOutdoorAirMethodValues READ systemOutdoorAirMethodValues);

    // TODO: Add relationships for objects related to this one, but not pointed to by the underlying data.
    //       Such relationships can be generated by the GenerateRelationships.rb script.
    Q_PROPERTY(boost::optional<openstudio::model::ModelObject> availabilitySchedule READ availabilityScheduleAsModelObject WRITE setAvailabilityScheduleAsModelObject);
   public:
    /** @name Constructors and Destructors */
    //@{

    ControllerMechanicalVentilation_Impl(const IdfObject& idfObject,
                                         Model_Impl* model,
                                         bool keepHandle);

    ControllerMechanicalVentilation_Impl(const openstudio::detail::WorkspaceObject_Impl& other,
                                         Model_Impl* model,
                                         bool keepHandle);

    ControllerMechanicalVentilation_Impl(const ControllerMechanicalVentilation_Impl& other,
                                         Model_Impl* model,
                                         bool keepHandle);

    virtual ~ControllerMechanicalVentilation_Impl() {}

    //@}

    /** @name Virtual Methods */
    //@{

    virtual const std::vector<std::string>& outputVariableNames() const;

    virtual IddObjectType iddObjectType() const;

    virtual std::vector<ScheduleTypeKey> getScheduleTypeKeys(const Schedule& schedule) const;

    //@}
    /** @name Getters */
    //@{

    // TODO: Check return type. From object lists, some candidates are: Schedule.
    Schedule availabilitySchedule() const;

    bool demandControlledVentilation() const;

    bool isDemandControlledVentilationDefaulted() const;

    std::string systemOutdoorAirMethod() const;

    bool isSystemOutdoorAirMethodDefaulted() const;

    // TODO: Handle this object's extensible fields.

    //@}
    /** @name Setters */
    //@{

    // TODO: Check argument type. From object lists, some candidates are: Schedule.
    bool setAvailabilitySchedule(Schedule& schedule);

    void setDemandControlledVentilation(bool demandControlledVentilation);

    void resetDemandControlledVentilation();

    bool setSystemOutdoorAirMethod(std::string systemOutdoorAirMethod);

    void resetSystemOutdoorAirMethod();

    // TODO: Handle this object's extensible fields.

    //@}
    /** @name Other */
    //@{

    ControllerOutdoorAir controllerOutdoorAir() const;
    //@}
   protected:
   private:
    REGISTER_LOGGER("openstudio.model.ControllerMechanicalVentilation");

    // TODO: Check the return types of these methods.
    // Optional getters for use by methods like children() so can remove() if the constructor fails.
    // There are other ways for the public versions of these getters to fail--perhaps all required
    // objects should be returned as boost::optionals
    boost::optional<Schedule> optionalAvailabilitySchedule() const;

    std::vector<std::string> systemOutdoorAirMethodValues() const;

    boost::optional<ModelObject> availabilityScheduleAsModelObject() const;

    bool setAvailabilityScheduleAsModelObject(const boost::optional<ModelObject>& modelObject);
  };

} // detail

} // model
} // openstudio

#endif // MODEL_CONTROLLERMECHANICALVENTILATION_IMPL_HPP

