/**********************************************************************
 *  Copyright (c) 2008-2014, Alliance for Sustainable Energy.
 *  All rights reserved.
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 **********************************************************************/

#ifndef MODEL_THERMOCHROMICGLAZING_IMPL_HPP
#define MODEL_THERMOCHROMICGLAZING_IMPL_HPP

#include "ModelAPI.hpp"
#include "Glazing.hpp"
#include "Glazing_Impl.hpp"

namespace openstudio {
namespace model {

namespace detail {

  /** ThermochromicGlazing_Impl is a Glazing_Impl that is the implementation class for ThermochromicGlazing.*/
  class MODEL_API ThermochromicGlazing_Impl : public Glazing_Impl {
    // TODO: Add relationships for objects related to this one, but not pointed to by the underlying data.
    //       Such relationships can be generated by the GenerateRelationships.rb script.
   public:
    /** @name Constructors and Destructors */
    //@{

    ThermochromicGlazing_Impl(const IdfObject& idfObject,
                              Model_Impl* model,
                              bool keepHandle);

    ThermochromicGlazing_Impl(const openstudio::detail::WorkspaceObject_Impl& other,
                              Model_Impl* model,
                              bool keepHandle);

    ThermochromicGlazing_Impl(const ThermochromicGlazing_Impl& other,
                              Model_Impl* model,
                              bool keepHandle);

    virtual ~ThermochromicGlazing_Impl() {}

    //@}

    /** @name Virtual Methods */
    //@{

    virtual const std::vector<std::string>& outputVariableNames() const;

    virtual IddObjectType iddObjectType() const;

    //@}
    /** @name Getters */
    //@{

    virtual double thickness() const;

    virtual double thermalConductivity() const;

    virtual double thermalConductance() const;

    virtual double thermalResistivity() const;

    virtual double thermalResistance() const;

    virtual double thermalTransmittance() const;

    virtual double thermalAbsorptance() const;

    virtual double thermalReflectance() const;

    virtual double solarTransmittance() const;

    virtual double solarAbsorptance() const;

    virtual double solarReflectance() const;

    virtual boost::optional<double> getVisibleTransmittance() const;

    virtual double visibleAbsorptance() const;

    virtual double visibleReflectance() const;

    double opticalDataTemperature() const;

    // TODO: Handle this object's extensible fields.

    //@}
    /** @name Setters */
    //@{

    virtual bool setThickness(double value);

    virtual bool setThermalConductivity(double value);

    virtual bool setThermalConductance(double value);

    virtual bool setThermalResistivity(double value);

    virtual bool setThermalResistance(double value);

    virtual bool setThermalTransmittance(double value);

    virtual bool setThermalAbsorptance(double value);

    virtual bool setThermalReflectance(double value);

    virtual bool setSolarTransmittance(double value);

    virtual bool setSolarAbsorptance(double value);

    virtual bool setSolarReflectance(double value);

    virtual bool setVisibleTransmittance(double value);

    virtual bool setVisibleAbsorptance(double value);

    virtual bool setVisibleReflectance(double value);

    void  setOpticalDataTemperature(double value);

    // TODO: Handle this object's extensible fields.

    //@}
    /** @name Other */
    //@{

    //@}
   protected:
   private:
    REGISTER_LOGGER("openstudio.model.ThermochromicGlazing");

    std::vector<Glazing> mf_glazings() const;

  };

} // detail

} // model
} // openstudio

#endif // MODEL_THERMOCHROMICGLAZING_IMPL_HPP

