source 'http://rubygems.org'

gem 'xml-simple'
gem 'json_pure'
gem 'openstudio-extension', github: 'nrel/openstudio-extension-gem', ref: 'f8038ad96b31c1f5d3d93ba73d9c09722c07d427'
gem 'tilt', github: 'rtomayko/tilt', ref: 'abe77eaf1b5f8da0a7e46135f'
