source 'http://rubygems.org'

gem 'xml-simple'
gem 'openstudio-extension', github: 'nrel/openstudio-extension-gem', ref: 'v0.4.0'
gem 'tilt', github: 'rtomayko/tilt', ref: 'abe77eaf1b5f8da0a7e46135f'
