compilers:
  - name: Visual Studio
    version: 12
    num_parallel_builds: 4
    cmake_extra_flags: -DBUILD_TESTING:BOOL=ON -DBUILD_SWIG:BOOL=ON -DBUILD_BOOST:BOOL=ON -DBUILD_QT:BOOL=OFF -DUSE_PCH:BOOL=ON -DBUILD_RUBY:BOOL=ON


