compilers:
  - name: "clang"
    version: "3.5"
    cmake_extra_flags: -DBUILD_TESTING:BOOL=ON -DBUILD_SWIG:BOOL=ON -DBUILD_BOOST:BOOL=OFF -DBUILD_QT:BOOL=OFF -DBUILD_RUBY:BOOL=OFF -DUSE_PCH:BOOL=ON -DBUILD_PACKAGE:BOOL=ON -DCPACK_BINARY_DEB:BOOL=ON -DCPACK_BINARY_NSIS:BOOL=OFF -DCPACK_BINARY_RPM:BOOL=OFF -DCPACK_BINARY_STGZ:BOOL=OFF -DCPACK_BINARY_TBZ2:BOOL=OFF -DCPACK_BINARY_TGZ:BOOL=OFF -DCPACK_BINARY_TZ:BOOL=OFF
    package_command: make package_deb
  - name: cppcheck
    compiler_extra_flags: --enable=warning  --suppress="*:*zlib*" --suppress="*:*sqlite*" --suppress="cppcheckError:*" --inline-suppr --suppress="syntaxError:*"

