compilers:
  - name: "gcc"
    version: "4.8"
    cmake_extra_flags: -DBUILD_TESTING:BOOL=ON -DBUILD_SWIG:BOOL=ON
    num_parallel_builds: 2
  - name: cppcheck
    compiler_extra_flags: --enable=warning  --suppress="*:*zlib*" --suppress="*:*sqlite*" --suppress="cppcheckError:*" --inline-suppr --suppress="syntaxError:*"
