source 'http://rubygems.org'

# gem 'openstudio-workflow', '2.4.0' # This is compatible with bundler 2.5 / Ruby 3.2 (OS 3.8+), but **NOT** already older than currently used at this time
gem 'tilt', '2.0.8'
