execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xfz "${CMAKE_CURRENT_BINARY_DIR}/OpenStudio-PAT-${PAT_SHA}.zip" WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
execute_process(COMMAND mv "${CMAKE_CURRENT_BINARY_DIR}/OpenStudio-PAT-${PAT_SHA}" "${CMAKE_CURRENT_BINARY_DIR}/OpenStudio-PAT" WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
execute_process(COMMAND "${NPM_COMMAND}" install WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/OpenStudio-PAT")
execute_process(COMMAND "${NPM_COMMAND}" install bower WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/OpenStudio-PAT")
execute_process(COMMAND "${CMAKE_CURRENT_BINARY_DIR}/OpenStudio-PAT/node_modules/.bin/bower" install WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/OpenStudio-PAT")
execute_process(COMMAND "${NPM_COMMAND}" run release WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/OpenStudio-PAT")
set(PAT_RESOURCE_PREFIX tmp/ParametricAnalysisTool.app/Contents/Resources/)
execute_process(COMMAND "${CMAKE_CURRENT_BINARY_DIR}/OpenStudio-PAT/node_modules/.bin/gulp" install-deps --exclude=openstudio --prefix=${PAT_RESOURCE_PREFIX} WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/OpenStudio-PAT")
