#!/bin/sh
# postinst script for bredsaal_laptop
#
# see: dh_installdeb(1)
set -e
case "$1" in
configure)
## Perhaps something needs to be configured in the future.
echo "Congratulations."
;;
abort-upgrade|abort-remove|abort-deconfigure)
;;
*)
echo "postinst called with unknown argument `$1'" >&2
exit 1
;;
esac
#DEBHELPER#
exit 0

