# gems in this file are packaged into openstudio.exe
# gems listed here should not have binary components
# gems listed here must be able to read resource files from the embedded files location

gem 'openstudio-workflow', :github => 'NREL/OpenStudio-workflow-gem', :ref => '37f56f9f54f3a9bd030820b47e77d5e72c71c64f'
gem 'openstudio-standards', :github => 'NREL/openstudio-standards', :ref => 'f960bc5cd123de066e116d170dfa85574c939fa6'

