# gems in this file are packaged into openstudio.exe
# gems listed here should not have binary components
# gems listed here must be able to read resource files from the embedded files location
# need to adjust hard coded paths in embedded_help.rb

gem 'openstudio-workflow', :github => 'NREL/OpenStudio-workflow-gem', :ref => 'b3300f79a831bd46e1848867fa34c40cfb166e88'

gem 'openstudio-standards', '= 0.1.10' 
#gem 'openstudio-standards', :github => 'NREL/openstudio-standards', :ref => '143191b8e72056c6d3396a20a6c8d961b1e1ca91'

gem 'rspec'
