# gems in this file are packaged into openstudio.exe
# gems listed here should not have binary components
# gems listed here must be able to read resource files from the embedded files location
# need to adjust hard coded paths in embedded_help.rb

gem 'openstudio-workflow', :github => 'NREL/OpenStudio-workflow-gem', :ref => '9a5a5100dae8881a2ffd8a3d7704e4f97711ad7e'
gem 'openstudio-standards', :github => 'NREL/openstudio-standards', :ref => 'ba8678eed4a2a4f3a950353482466bb4bb8a2072'

gem 'rspec'
